---
image:
    file: .gitpod/Dockerfile
    context: .gitpod
checkoutLocation: gopherbot
workspaceLocation: .
tasks:
- init: git clone https://github.com/lnxjedi/robot.skel.git && ln -s ../gopherbot/gopherbot robot.skel/gopherbot && ln -s ../gopherbot/.env robot.skel/.env
- command: make -C gopherbot
