---
image:
    file: .gitpod/Dockerfile
    context: .gitpod
checkoutLocation: gopherbot
workspaceLocation: .
tasks:
- init: make -C gopherbot
- init: ./gopherbot/.gitpod/gotools.sh
- command: ./gopherbot/.gitpod/setup.sh
  openIn: main
ports:
- port: 8080
  onOpen: ignore