name: build-release

on:
  push:
    tags:
    - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.
      - name: Test
        run: make test
      - name: Build
        run: make dist
      - name: Release
        # softprops/action-gh-release v0.1.12
        uses: softprops/action-gh-release@2d72d869af3bf23602f9593a1e3fd739b80ac1eb
        with:
          files: gopherbot-linux-amd64.tar.gz
          body: |
            See the [CHANGELOG](https://github.com/lnxjedi/gopherbot/blob/main/CHANGELOG.md)

  build-containers:
    runs-on: ubuntu-latest
    # The only owner with the quay.io credentials
    if: ${{ github.repository_owner	 == 'lnxjedi' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.
      - name: Build
        run: make dist
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: "lnxjedi+autobuild"
          password: ${{ secrets.QUAY_LNXJEDI_TOKEN }}
      -
        name: Docker meta - minimal
        id: meta-minimal
        uses: docker/metadata-action@v3
        with:
          images: quay.io/lnxjedi/gopherbot
      -
        name: Build and push minimal
        uses: docker/build-push-action@v2
        with:
          context: .
          file: resources/containers/minimal/Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-minimal.outputs.tags }}
      -
        name: Docker meta - dev
        id: meta-dev
        uses: docker/metadata-action@v3
        with:
          images: quay.io/lnxjedi/gopherbot-dev
      -
        name: Build and push dev
        uses: docker/build-push-action@v2
        with:
          context: .
          file: resources/containers/dev/Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-dev.outputs.tags }}
      -
        name: Docker meta - theia
        id: meta-theia
        uses: docker/metadata-action@v3
        with:
          images: quay.io/lnxjedi/gopherbot-theia
      -
        name: Build and push theia
        uses: docker/build-push-action@v2
        with:
          context: .
          file: resources/containers/theia/Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-theia.outputs.tags }}
